language: java
install: true
os: linux
jdk:
- openjdk11
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
- make ci
env:
  global:
  - secure: cfraD6KRon2uVe84GECB/W2H/ZoePrivrQGY1AwmBleCVFMJh3uBnsQHpVJNwDz3SzaPVVK1ZbVrHKBbYmNet6WWAPeE1rUzHBXenpzF5BAHQJG5RQrtbVZG5gOCRJ3lpEk58W6DbNWqOsDWr0/Auvi6on5HKdSMfbHY51A7lVhO73tk3+thtTy5wdjg6vTlZwfptoHUQyJ+jcVEwMTaGTC5UyfbLpBF9mPRrc7uaRm+9EqsISxxVaJOTijWeSwgeVD14hIFTgR2NhK/9jEhn1j3wV6302vhUanBAB8+u9htllDg6xYgautRPX4bnBsghHgbwzKJzUGiXZ3v1InObEhaXd1Aew9nfSZ28gHZMU+8x+Lx6ZgkCdtG6LCsdL0ByplOOGFtB60bLC7weluiuuSJJ2+d57wKY4/+jA+xHhZDqOdMb3N9oKY9LgcuMtPWDr8pz+3LHFI+uFXMyEEKUd8rFhkZzmveF2goYTSi+WPQFk5XqWB3bt/qB/jM0luavzig5WQg4+cHyflmXAqZwmapk4Q/GuAp10+qv3Fwqcz9MS8OF2i3fIUh6U8YwrcDKaILYqwmJFDidErdLxE5gFDhdoq1bz0pmEKnChhY1X7CMK/WrigWZIrBZzl75aKAI7MXoAScgPzUjmsraEzMmR0PT53WHrDOhfpUmhZioFo=
  - secure: As2CpUV+0MPQ+vu7R8DCBVqDkhBPk0o5P3GZrYszmfXQTmiCEZM530rjzom5w1I5RAdJzJhggkrM8yAbl3yfSqWUFDfTJ4nuaJ4WfRa6RE9MoNPMJNlGHIiVTOHB/hvdXyEd9ZKuM8yyiPtFyHSnouWwpMfVcygXONjgNdhbBX2je2gjmC8XfmY/S8cQ5iqEd5S26kxP241mbRamk6yK496f4QUolcpMSfz9cz8mJftQZ8R/5hnDOkzRcWakEeg+ahnLC1lIqLFQakYToBb0R+Wlklz4B4QTbbElfIHa1vUnQBkPB8X4bKyEhZ6Lw2L9I9SD0I/GZb8z64QrdIZBsNLtjEShy8Z+u7dbXGBia96f4pd/4BH6fibhRZj+3MFR3X8vYfCuQVYF6Ll3pMAmQ58+AXs1OS2MCgetU1SYJA+p0R5KyF3RwA9AJ4DOTmNhxnmUooGVtDv+wrY1nO1O++Em0z6ovlOl+IWd4bs33MfiMhu0h/dO3jFWYGu1mYF9lbHKWClRW79yBEDk2gtWVp7LodRjQYh+qAFDlvFnNWvimwAoIgbV5yyEOiC6EtqWAGLLZWboeLwGbjHkXwUIcGcnpRM+KzbRWGkILA6/3I+LmSJmwu/RnLHjCt6EkswGwZ2laoCUhoyYsbkyM631fHn6LngKfX5YBcoX9sxVgnU=
  - secure: IJY84ygU/2tDUw7LZToIlgQ6LjZT2ilpzrWP+vLmZPNkA3QA7TPsCVNrLoTeqmcR0YtAh1a+MEecz1PsjEDrc5Kke8C/NNbcY4rQb71H3rs5hM0ZRLs7ethmtvZ9h1mEAx45lRgbLp44/6SMeBlCYilAuw9kwheCm+Ywnoqyvcf03DSGn1MEAQa/H9ASrWc/EBlK6eXURPhTpcOQpRm7eTodSKoveb+tQ27ixp3p7UteFJ7LzPmYSmO1JApdaSUFbblFWT0z+h4+rXWHqZRwLPUtChCIDrrZ36EMQBqgeKbeGs8AnMzvWN3NkfOGqELSASW0MP4SAEoVOl6xEjWchU5/EuN5L34T6UpYbL6Hrxx3Kcw7cUl0m9u1aUgTLvwgMM4T5l5FszQJ1437ob9HoyGVO3lWH57HWcnas01RB8ZHVPrzkiPBznjnlAXSSoRtOn7NE/IYl3XW9rBcp3ktYvhS8esC1R8zE6kakjCuuhTLlv4co/5i5fCJApxed8dcigAJOP0V8mNhyXV2Kw/I9JA6aO4uR5o6gOiHOkMFE+mOvjXHFN6bm9BdF3Xhidm5QLhcZUSHLIWlaHJ1DloqSvlv1gPF0T5n45Ymy7yuByauYG2m3Kt6BqhpV864UAigYO4G9Xs2XTsOVG/y0gSdK7ovO78H2Gb/Rh3wq1uXbGk=
